// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTUoqLoOTStx6WfyRjKfUWJEnOCByDiSA',
    appId: '1:7991489002:web:40838c6a132b9f6cf30293',
    messagingSenderId: '7991489002',
    projectId: 'hiiii-3347c',
    authDomain: 'hiiii-3347c.firebaseapp.com',
    storageBucket: 'hiiii-3347c.firebasestorage.app',
    measurementId: 'G-V6ELSBFLK9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDECovGeeY_ixssp8jM_OVTuADXRcOafSY',
    appId: '1:7991489002:android:c7e488b25633693df30293',
    messagingSenderId: '7991489002',
    projectId: 'hiiii-3347c',
    storageBucket: 'hiiii-3347c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZI2Jzo6thriXq_xOBdHq1SdyJ1Wi1QMM',
    appId: '1:7991489002:ios:2aa351306b03bfd5f30293',
    messagingSenderId: '7991489002',
    projectId: 'hiiii-3347c',
    storageBucket: 'hiiii-3347c.firebasestorage.app',
    iosBundleId: 'com.example.ui',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZI2Jzo6thriXq_xOBdHq1SdyJ1Wi1QMM',
    appId: '1:7991489002:ios:2aa351306b03bfd5f30293',
    messagingSenderId: '7991489002',
    projectId: 'hiiii-3347c',
    storageBucket: 'hiiii-3347c.firebasestorage.app',
    iosBundleId: 'com.example.ui',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBTUoqLoOTStx6WfyRjKfUWJEnOCByDiSA',
    appId: '1:7991489002:web:f0eb91ccadf08761f30293',
    messagingSenderId: '7991489002',
    projectId: 'hiiii-3347c',
    authDomain: 'hiiii-3347c.firebaseapp.com',
    storageBucket: 'hiiii-3347c.firebasestorage.app',
    measurementId: 'G-T27ZFLSB93',
  );

}